import { IBook } from "@/lib/types/Book";

const books_fixture: IBook[] = [
  {
    "id": 1,
    "title": "The Mysterious Island",
    "author": { "firstName": "Jules", "lastName": "Verne" },
    "averageRate": 4.7,
    "coverFileId": "fixture-book.jpg",
    "isForRent": false,
    "price": 10,
    "reviews": 1200,
    "isbn": "978-2-07-036002-4",
    "editor": "Penguin",
    "genre": "NOVEL",
    "theme": "TRAVEL_EXPLORATION",
    "otherTheme": null,
    "format": "PAPERBACK",
    "isPhysicalFormat": true,
    "languageCode": "fr",
    "targetAudience": "ENTERTAINMENT"
  },
  {
    "id": 2,
    "title": "1984",
    "author": { "firstName": "George", "lastName": "Orwell" },
    "averageRate": 4.8,
    "coverFileId": "fixture-book.jpg",
    "isForRent": true,
    "price": 6,
    "reviews": 2300,
    "isbn": "978-0-452-28423-4",
    "editor": "Secker & Warburg",
    "genre": "NOVEL",
    "theme": "LIBERTY_AND_OPPRESSION",
    "otherTheme": null,
    "format": "POCKET",
    "isPhysicalFormat": true,
    "languageCode": "en",
    "targetAudience": "ACADEMIC"
  },
  {
    "id": 3,
    "title": "The Divine Comedy",
    "author": { "firstName": "Dante", "lastName": "Alighieri" },
    "averageRate": 4.6,
    "coverFileId": "fixture-book.jpg",
    "isForRent": false,
    "price": 12,
    "reviews": 1500,
    "isbn": "978-0-14-044895-5",
    "editor": "Penguin Classics",
    "genre": "POESY",
    "theme": "GOOD_AND_EVIL",
    "otherTheme": null,
    "format": "EPUB",
    "isPhysicalFormat": false,
    "languageCode": "it",
    "targetAudience": "ACADEMIC"
  },
  {
    "id": 4,
    "title": "The Little Prince",
    "author": { "firstName": "Antoine", "lastName": "de Saint-Exupéry" },
    "averageRate": 4.9,
    "coverFileId": "fixture-book.jpg",
    "isForRent": true,
    "price": 8,
    "reviews": 3400,
    "isbn": "978-2-07-040850-2",
    "editor": "Gallimard",
    "genre": "CHILDREN",
    "theme": "DREAM_IMAGINARY",
    "otherTheme": null,
    "format": "PAPERBACK",
    "isPhysicalFormat": true,
    "languageCode": "fr",
    "targetAudience": "ENTERTAINMENT"
  },
  {
    "id": 5,
    "title": "Frankenstein",
    "author": { "firstName": "Mary", "lastName": "Shelley" },
    "averageRate": 4.5,
    "coverFileId": "fixture-book.jpg",
    "isForRent": false,
    "price": 9,
    "reviews": 1800,
    "isbn": "978-0-19-953715-0",
    "editor": "Oxford University Press",
    "genre": "NOVEL",
    "theme": "SCIENCE_PROGRESS_AND_EXCESSES",
    "otherTheme": null,
    "format": "EPUB",
    "isPhysicalFormat": false,
    "languageCode": "en",
    "targetAudience": "ACADEMIC"
  },
  {
    "id": 6,
    "title": "Moby Dick",
    "author": { "firstName": "Herman", "lastName": "Melville" },
    "averageRate": 4.4,
    "coverFileId": "fixture-book.jpg",
    "isForRent": true,
    "price": 7,
    "reviews": 2000,
    "isbn": "978-0-553-21311-7",
    "editor": "Bantam Classics",
    "genre": "NOVEL",
    "theme": "DESTINY_FREEWILL",
    "otherTheme": null,
    "format": "PAPERBACK",
    "isPhysicalFormat": true,
    "languageCode": "en",
    "targetAudience": "ENTERTAINMENT"
  },
  {
    "id": 7,
    "title": "Brave New World",
    "author": { "firstName": "Aldous", "lastName": "Huxley" },
    "averageRate": 4.7,
    "coverFileId": "fixture-book.jpg",
    "isForRent": false,
    "price": 10,
    "reviews": 3100,
    "isbn": "978-0-06-085052-4",
    "editor": "HarperCollins",
    "genre": "NOVEL",
    "theme": "SCIENCE_PROGRESS_AND_EXCESSES",
    "otherTheme": null,
    "format": "POCKET",
    "isPhysicalFormat": true,
    "languageCode": "en",
    "targetAudience": "ACADEMIC"
  }
];

export default books_fixture;
